apiVersion: v1
items:
- apiVersion: litmuschaos.io/v1alpha1
  description:
    message: |
      Deletes a pod belonging to a deployment/statefulset/daemonset
  kind: ChaosExperiment
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"litmuschaos.io/v1alpha1","description":{"message":"Deletes a pod belonging to a deployment/statefulset/daemonset\n"},"kind":"ChaosExperiment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"chaosexperiment","app.kubernetes.io/part-of":"litmus","app.kubernetes.io/version":"2.14.0","name":"pod-delete"},"name":"pod-delete","namespace":"default"},"spec":{"definition":{"args":["-c","./experiments -name pod-delete"],"command":["/bin/bash"],"env":[{"name":"TOTAL_CHAOS_DURATION","value":"15"},{"name":"RAMP_TIME","value":""},{"name":"FORCE","value":"true"},{"name":"CHAOS_INTERVAL","value":"5"},{"name":"PODS_AFFECTED_PERC","value":""},{"name":"LIB","value":"litmus"},{"name":"TARGET_PODS","value":""},{"name":"NODE_LABEL","value":""},{"name":"SEQUENCE","value":"parallel"}],"image":"litmuschaos/go-runner:2.14.0","imagePullPolicy":"Always","labels":{"app.kubernetes.io/component":"experiment-job","app.kubernetes.io/part-of":"litmus","app.kubernetes.io/version":"2.14.0","name":"pod-delete"},"permissions":[{"apiGroups":[""],"resources":["pods"],"verbs":["create","delete","get","list","patch","update","deletecollection"]},{"apiGroups":[""],"resources":["events"],"verbs":["create","get","list","patch","update"]},{"apiGroups":[""],"resources":["configmaps"],"verbs":["get","list"]},{"apiGroups":[""],"resources":["pods/log"],"verbs":["get","list","watch"]},{"apiGroups":[""],"resources":["pods/exec"],"verbs":["get","list","create"]},{"apiGroups":["apps"],"resources":["deployments","statefulsets","replicasets","daemonsets"],"verbs":["list","get"]},{"apiGroups":["apps.openshift.io"],"resources":["deploymentconfigs"],"verbs":["list","get"]},{"apiGroups":[""],"resources":["replicationcontrollers"],"verbs":["get","list"]},{"apiGroups":["argoproj.io"],"resources":["rollouts"],"verbs":["list","get"]},{"apiGroups":["batch"],"resources":["jobs"],"verbs":["create","list","get","delete","deletecollection"]},{"apiGroups":["litmuschaos.io"],"resources":["chaosengines","chaosexperiments","chaosresults"],"verbs":["create","list","get","patch","update","delete"]}],"scope":"Namespaced"}}}
    creationTimestamp: "2023-10-02T05:56:24Z"
    generation: 1
    labels:
      app.kubernetes.io/component: chaosexperiment
      app.kubernetes.io/part-of: litmus
      app.kubernetes.io/version: 2.14.0
      name: pod-delete
    name: pod-delete
    namespace: default
    resourceVersion: "138109"
    uid: 6c0dbc39-a11f-41a6-9c35-1986cd766892
  spec:
    definition:
      args:
      - -c
      - ./experiments -name pod-delete
      command:
      - /bin/bash
      env:
      - name: TOTAL_CHAOS_DURATION
        value: "15"
      - name: RAMP_TIME
        value: ""
      - name: FORCE
        value: "true"
      - name: CHAOS_INTERVAL
        value: "5"
      - name: PODS_AFFECTED_PERC
        value: ""
      - name: LIB
        value: litmus
      - name: TARGET_PODS
        value: ""
      - name: NODE_LABEL
        value: ""
      - name: SEQUENCE
        value: parallel
      image: litmuschaos/go-runner:2.14.0
      imagePullPolicy: Always
      labels:
        app.kubernetes.io/component: experiment-job
        app.kubernetes.io/part-of: litmus
        app.kubernetes.io/version: 2.14.0
        name: pod-delete
      permissions:
      - apiGroups:
        - ""
        resources:
        - pods
        - deployments
        verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - deletecollection
      - apiGroups:
        - ""
        resources:
        - events
        verbs:
        - create
        - get
        - list
        - patch
        - update
      - apiGroups:
        - ""
        resources:
        - configmaps
        verbs:
        - get
        - list
      - apiGroups:
        - ""
        resources:
        - pods/log
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - ""
        resources:
        - pods/exec
        verbs:
        - get
        - list
        - create
      - apiGroups:
        - apps
        resources:
        - deployments
        - statefulsets
        - replicasets
        - daemonsets
        verbs:
        - list
        - get
      - apiGroups:
        - apps.openshift.io
        resources:
        - deploymentconfigs
        verbs:
        - list
        - get
      - apiGroups:
        - ""
        resources:
        - replicationcontrollers
        verbs:
        - get
        - list
      - apiGroups:
        - argoproj.io
        resources:
        - rollouts
        verbs:
        - list
        - get
      - apiGroups:
        - batch
        resources:
        - jobs
        verbs:
        - create
        - list
        - get
        - delete
        - deletecollection
      - apiGroups:
        - litmuschaos.io
        resources:
        - chaosengines
        - chaosexperiments
        - chaosresults
        verbs:
        - create
        - list
        - get
        - patch
        - update
        - delete
      scope: Namespaced
kind: List
metadata:
  resourceVersion: ""